# Generated by Django 5.0.3 on 2024-07-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='entry_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('운동', '운동'), ('식단', '식단'), ('공부', '공부'), ('취미', '취미'), ('자기계발', '자기계발')], max_length=100),
        ),
    ]
