<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-07-04 03:52
=======
# Generated by Django 5.0.3 on 2024-07-03 12:21
>>>>>>> ff59eaba0d9c59d00715661d88a6f144da1d619b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='entry_number',
<<<<<<< HEAD
            field=models.PositiveIntegerField(null=True),
=======
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
>>>>>>> ff59eaba0d9c59d00715661d88a6f144da1d619b
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('운동', '운동'), ('식단', '식단'), ('공부', '공부'), ('취미', '취미'), ('자기계발', '자기계발')], max_length=100),
        ),
    ]
