# Generated by Django 5.0.3 on 2024-07-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_entry_number_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='entry_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
