# Generated by Django 5.0.3 on 2024-07-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
    ]
