# Generated by Django 5.0.3 on 2024-07-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='frequency',
            field=models.CharField(default=True, max_length=5),
        ),
    ]
